import { DJ } from '../../_models/dj'; 

export const DJS: DJ[] = [


{name:"Briki",info:"Briki, is a Tunisian artist, DJ, and music producer based in Tunis. He is recognized for his significant role in shaping and developing the local electronic music scene in Tunisia. Briki is the founder and owner of Warok Music and Are You Alien Records, two labels that contribute to the promotion and growth of electronic music in the region. His work as a DJ and producer has made him a prominent figure in Tunisia’s contemporary music landscape, particularly within the techno genre.",img:"assets/images/djs/Briki.jpeg",sound:"https://soundcloud.com/eythbriki",insta:"https://www.instagram.com/_____briki/",expanded:false},


{name:"Caleb Jackson",info:"Hailing from the vibrant Australian dance scene Caleb is a prolific producer and DJ with a deep love for his craft. His sound is energetic groove driven psychedelic house music with a focus on fusing genres and pushing boundaries. Gaining recognition in the scene with a steady string of releases on respected international labels such as MicroHertz, Metafloor, Elrow, Pitch, Desert Hearts and many more, 4 Ep’s collecting spots in the Beatport top 10. As a DJ he has a long list of coveted party’s and festivals under his belt with highlight performances at Fabric, Thuishaven, Sankeys, Lost Paradise, Burning Man, Beyond The Valley, S.A.S.H, Breakfast Club, Koko (London) and a residency at Sydney’s Lost Sunday’s.",img:"assets/images/djs/Caleb_Jackson.jpeg",sound:"https://soundcloud.com/caleb-jackson-41",insta:"https://www.instagram.com/calebjacks.on/?hl=en",expanded:false},

{name:"Enrica Falque B2B Anna Wall",info:" Enrica Falqui is a Sardinian-born, Berlin-based DJ and producer exploring the depths of techno, electro, and ambient. Her 2021 solo EP Plexus blends dreamy soundscapes with dance floor energy. As part of ERIS, she earned acclaim with releases on Cabaret Recordings, including the Resident Advisor-recognized track ‘Moloko.’ She also collaborates with Grand River in the experimental project Yhdessa. Enrica is driven by a passion for sound, spending countless hours crafting emotionally rich, immersive music.Anna began DJing off-grid London parties in 2010, mixing dub techno, 90s house, and acid with a unique edge. She runs The Bricks label, known for its sold-out vinyl releases, and showcases her eclectic taste on Rinse FM. Her versatile sets have taken her to top clubs and festivals across Europe and Latin America. Anna also launched Dream Theory, an ambient and experimental label, releasing the acclaimed album Missing Moments. With new solo and collaborative projects ahead, 2025 looks promising.",img:"assets/images/djs/Anna Wall.jpg", img2:"assets/images/djs/Enrica Falqui.jpg", sound:"https://soundcloud.com/enricafalqui", insta:"https://www.instagram.com/enricafalqui/?hl=en",sound2:"https://soundcloud.com/djannawall",insta2:"https://www.instagram.com/djannawall/?hl=en",expanded:false},

{name:"Eva Crystaltips",info:"Originally from France, Eva Crystaltips has carved out a dynamic and influential career in the world of DJing. Her journey began in the vibrant city of Edinburgh, where she quickly made a name for herself by securing weekly and monthly DJ residencies in some of the Scottish capital's most renowned bars and clubs. She then creating her own party, ‘Can You DigIt,’ which she launched at the iconic Sneaky Pete’s in early 2020, just before she moved away from Scotland.",img:"assets/images/djs/Eva Cristaltips.jpeg",sound:"https://soundcloud.com/evacrystaltips",insta:"https://www.instagram.com/evacrystaltips/",expanded:false},

{name:"Fimiani B2B Geelane",info:"FIMIANI aka BPlan is an Italian DJ, producer, and vinyl digger known for his soulful house sound rooted in funk, soul, and disco. Based on the island of Ischia (Naples), he’s been running parties since 2009 and joined the Toy Tonics crew in 2020. He co-runs the vinyl-only label Caffè Corretto Edits, reworking rare Italian '70s records into modern dancefloor gems—some featured on the Toy Tonics Italomania compilation. His tracks have gained support from DJs like Dave Lee and Lele Sacchi and airplay on stations like NTS, Radio Nova, and M2O. He’s also shared stages with Dan Shake, Folamour, Kapote, and more.",info2:"Gee Lane is a Venezuelan DJ based in Barcelona and a close friend of the Toy Tonics crew. Known for her vibrant sets blending funky future house, rare disco edits, soulful techno, and Latin-infused rhythms, she perfectly captures the Toy Tonics vibe. Under her alias VIR-GINIE, she’s built a strong reputation for her deep musical knowledge, genre-bending flexibility, and razor-sharp technique. She’s played top festivals and clubs like Sónar, Primavera Sound, DGTL, and Brunch-In The Park, and has shared stages with icons like Laurent Garnier, Honey Dijon, and Louie Vega. In 2023, she’s set to release her debut EP on Toy Tonics. Gee Lane also curates the ‘Table For Two’ radio show on Radio D59B, spotlighting some of the industry’s finest talents.",img:"assets/images/djs/fimiani.jpg",img2: "assets/images/djs/Gee lane.jpg",sound:"https://soundcloud.com/virginie_aka_vir",insta:"https://www.instagram.com/_gee_lane_/",sound2:"https://soundcloud.com/bplan_fimiani",insta2:"https://www.instagram.com/bplan__fimiani/",expanded:false},

{name:"Finca Amour",info:"Finca Amour is the duo of Franca and Mimi Love, blending raw rhythm with dreamy storytelling on the dancefloor. Franca delivers high-energy vinyl grooves with sharp crowd intuition, while Mimi weaves deep house and cosmic disco into an ethereal sound. Together, they create sets that blur genres and stir emotions. Every performance is a journey and a love letter to the dance floor." ,img:"assets/images/djs/Finca_Amour.jpg",sound:"https://soundcloud.com/francaplays",insta:"https://www.instagram.com/franca_plays/?hl=en",sound2:"https://soundcloud.com/spreedelay",insta2:"instagram.com/mimi_love_berlin/"
,expanded:false},

{name:"Frankey & Sandrino",info:"Frankey & Sandrino are a long-standing electronic duo known for their open-minded, genre-blending productions and a decade-plus commitment to artistic integrity over trends. Since forming in 2009, they’ve released on respected labels like Innervisions, Kompakt, and their own Sum Over Histories, earning a reputation for deeply original and emotionally resonant music. Their creative process is rooted in intuition and balance, drawing from Frankey’s instrumental training and Sandrino’s eclectic musical background. With standout tracks like ‘Acamar’ and ‘Ways of the Sun,’ and performances at iconic venues like Fabric and Stereo, they continue to inspire dance floors worldwide. In 2024, the duo returns with fresh releases that push boundaries while staying true to their soulful, signature sound.",img:"assets/images/djs/Frankey&Sandrino.jpg",sound:"https://soundcloud.com/frankeyandsandrino",insta:"https://www.instagram.com/frankey_and_sandrino/?hl=en",expanded:false},


{name:"Hearthug",info:"Hearthug is another leading Tunisian DJ and producer, celebrated for his hypnotic, rhythm-driven sets that blend traditional Tunisian elements with modern techno and house. As a co-founder of the Vibe Out collective and event series, Hearthug has played a key role in fostering experimental electronic music in Tunis. He has released music on Warok Music and international labels like Safari Numerique, and his performances at regional festivals have helped bring Tunisia’s underground electronic scene to a global audience. Hearthug’s work reflects a creative fusion of North African heritage and cutting-edge club culture.",img:"assets/images/djs/hearthug.jpg",sound:"https://soundcloud.com/hearthug", insta:"https://www.instagram.com/hearthug_/",expanded:false},


{name:"Jarl Flamar",info:"Jarl Flamar is a multi-instrumentalist and DJ who blends Middle Eastern instruments with deep, hypnotic oriental house. Known for his precise sound and immersive style, he’s played major festivals like Fusion, Wonderfruit, and Ozora. His music transports listeners to a reimagined Mesopotamia, rich with rhythm and mysticism. Whether in clubs or open-air venues, his sets create powerful, dreamlike experiences across the globe.",img:"assets/images/djs/Jarl Flammar.JPG" ,sound:"https://soundcloud.com/jarlflamar",insta:"https://www.instagram.com/jarl_flamar/",expanded:false},


{name:"Labouts B2B Woddd",info:"Hailing from Bordeaux, Leopold aka. Labouts embarked on his artistic journey in Paris at the young age of 20. Immersed in the illustrious atmosphere of the esteemed Yoyaku record shop, he meticulously curated a formidable collection of vinyl, honing his mixing skills along the way. Additionally, Leopold holds the distinction of being the co-founder and resident DJ of the acclaimed Hillbilly crew, further solidifying his presence in the thriving music scene.",info2:"Woddd, a sonic explorer entrenched in the heart of the capital for nearly ten years, stands as the esteemed curator of the renowned Yoyaku record store, a venture he co-founded and nurtured into existence nestled amidst the vibrant landscape of Belleville. His discerning prowess as a crate digger has extended to his recent endeavors at Chapelle XIV, an emerging multicultural hub in the heart of Paris.", img:"assets/images/djs/Labouts.jpg",img2:"assets/images/djs/WODDD.jpeg",sound:"https://soundcloud.com/laboutsmusic",insta:"https://www.instagram.com/labouts_/",sound2:"https://soundcloud.com/woddd",insta2:"https://www.instagram.com/woddd_stock/",expanded:false},

{name:"Luca Olivotto",info:"Berlin-based producer, DJ, and label owner Luca Olivotto channels his expertise into crafting independent and aesthetically pleasing electronic music, with a particular focus on House and Disco House. His labels, Vinyl label Small Great Things. At A Glance and the little digital Endless Music, are driven by a dedication to originality and creativity, showcasing meticulously crafted music with distinctive character.",img:"assets/images/djs/Luca Olivotto.jpg" ,sound:"https://soundcloud.com/lucaolivotto",insta:"https://www.instagram.com/lucaolivotto/",expanded:false},

{name:"LUNA CITY EXPRESS live",info:"Luna City Express, the duo of Norman Weber and Marco Resmann, has been a cornerstone of the electronic and house music scene since forming in 2000. Known for their dynamic DJ sets and consistently evolving sound, they’ve earned international acclaim with releases on top labels like Moon Harbour, Exploited, and 20/20 Vision. Their 2005 debut single ‘Fresh’ became an instant club classic, followed by enduring tracks like ‘Mr Jack’ from their album Hello from Planet Earth. Rooted in house but influenced by everything from funk and disco to hip-hop and acid jazz, their sound reflects both deep musical roots and forward-thinking production. Over two decades in, Luna City Express continues to shape modern house music with unmistakable style and energy.",img:"assets/images/djs/Luna city Express.jpg",sound:"https://soundcloud.com/luna-city-express",insta:"https://www.instagram.com/lunacityexpress/",expanded:false},

{name:"Madmotormiquel & Kotoe",info:"Madmotormiquel and Kotoe’s B2B sets are more than performances, they’re explosive, spontaneous journeys driven entirely by the energy of the dance floor. Madmotormiquel brings deep, driving baselines shaped by his roots in West Berlin’s underground, while Kotoe blends her Japanese-Brazilian heritage into grooves influenced by Tokyo, Rio, and Berlin. Their chemistry creates a raw, genre-fluid sound that flows freely through house, acid, disco, and beyond. Each set is improvised and instinctual, with no gimmicks, just pure, unfiltered connection with the crowd. It’s the kind of experience where the music decides the direction, and the floor follows.",img:"assets/images/djs/Kotoe.jpg",img2:"assets/images/djs/Madmotormiquel.jpg",sound:"https://soundcloud.com/madmotormiquel",insta:"https://www.instagram.com/madmotormiquel/",expanded:false},

{name:"Magda B2B Jonny Rock",info:"Magda is a boundary-pushing DJ, producer, and multidisciplinary artist. Born in Poland and raised in Detroit, she rose through the city’s underground scene and joined Richie Hawtin’s Minus label in 1998. Known for her adventurous sets and intricate mixes, she’s played top clubs and festivals worldwide. Her debut album From The Fallen Page and remixes for artists like Depeche Mode showcase her studio talent. She collaborates on experimental projects like Cornerbred and DTR, and co-runs the Items & Things label. Beyond music, she’s also involved in tequila, design, and tech ventures.",info2:"& about Johnny- well, if you know … you know...",img:"assets/images/djs/Magda.jpg",img2:"assets/images/djs/johnny Rock.jpg", sound:"https://soundcloud.com/magda-official",insta:"https://www.instagram.com/magda_official/", sound2:"https://soundcloud.com/jonnyrock",insta2:"https://www.instagram.com/captainrocklock/?hl=en",expanded:false},

{name:"Nephews",info:"Nephews is a dynamic DJ and producer duo from Beirut and Berlin, known for blending nostalgic '90s and 2000s vibes with modern house sounds. Their releases span respected labels like Ravanelli Disco Club, Wolf Music, and APRH Records, including work as part of Love Ensemble. In Berlin, they've become a vital force in the club scene, lighting up venues and curating their own party series, ‘disco-very.’ Their music is rich with bouncy beats, dreamy synths, and sample-driven energy, moving seamlessly from introspective to club-ready. With radio features on HÖR, Metro Beirut, and more, Nephews continue to shape the global underground sound." ,img:"assets/images/djs/nephews.jpg",sound:"https://soundcloud.com/nephewsmusik",insta:"https://www.instagram.com/nephewsmusik/?hl=en",expanded:false},

{name:"Pascal Moscheni",info:"Pascal Moscheni is a DJ and sound artist known for his eclectic, sophisticated style, blending Italian dream house, percussive rhythms, acid, trance, and Balearic influences. His sets are marked by deep digging, rare selections, and a love for dreamy, disco-infused grooves. Moscheni is closely involved with the influential Paris-based collective Yoyaku, which is shaping the European minimal and house scene. Whether performing at top festivals or curating soundtracks for fashion shows, he stands out for his innovative, emotionally resonant approach to electronic music.",img:"assets/images/djs/Pascal moscheni.jpeg",sound:"https://soundcloud.com/pascalmoscheni",insta:"https://www.instagram.com/pascalmoscheni/",expanded:false},

{name:"Quadrakey",info:"Quadrakey are a Berlin-based DJ and producer duo known for their deep, groovy house sound. Active since the early 2000s and forming Quadrakey in 2007, they founded Tooman Records in 2015 with the motto ‘House music with a deep passion.’ Influenced by 90s house, funk, soul, and hip-hop, their sets and productions blend emotion, melody, and rhythm. Their carefully curated label and timeless style continue to make a strong mark on the scene." ,img:"assets/images/djs/Quadrakey.jpg",sound:"https://soundcloud.com/quadrakey",insta:"https://www.instagram.com/quadrakey/",expanded:false},

{name:"Sarah Wild",info:"Sarah Wild is a Berlin-based DJ and producer who blends disco, Italo, and acid sounds into her unique take on electronic dance music. Raised in Jena and musically trained in saxophone and piano, she grew up touring Europe with her father’s surf-rock band. Since launching her solo project in 2016, she’s played top festivals like Fusion and clubs like Sisyphos and Watergate. Her energetic sets and distinctive style have earned her releases on labels like Permanent Vacation and Feines Tier. Sarah continues to shape the club scenes in Berlin and beyond with her bold, groovy sound.",img:"assets/images/djs/Sarah Wild.jpeg",sound:"https://soundcloud.com/wildsarah",insta:"https://www.instagram.com/sarahwild_music/?hl=en",expanded:false},

{name:"Sedef Adasi",info:"Sedef Adasï is a DJ, producer, and host of HAMAM Nights, known for her dynamic sets and dedication to fostering local and inclusive club culture. Based in her hometown of Augsburg, she founded HAMAM Nights in 2017, bringing global nightlife talent to the City Club while promoting diversity and regional connection. Her residencies at Munich’s BLITZ and Berlin’s Panorama Bar reflect her growing influence across Germany and beyond. Musically versatile, Sedef blends elements of techno, acid, house, breaks, proto-disco, and 80s/90s pop into a high-energy, cohesive sound. Her style reflects both deep musical passion and a commitment to community and continuity. Through her work, she continues to tour the HAMAM spirit of inclusivity across dancefloors worldwide.",img:"assets/images/djs/sedef_adasi.jpeg",sound:"https://soundcloud.com/sedefadasi",insta:"https://www.instagram.com/sedeffadasi/?hl=en",expanded:false},

{name:"Siggatunez",info:"Siggatunez is a Berlin-based DJ, producer, and founder of TIEFFREQUENT and GOOEY, a label and event series. Rooted in 90s Hip-Hop, MOTOWN, and East German Funk, he started producing music after being inspired by his family's vinyl collection. He co-founded the House event SUCIO in Frankfurt before moving to Berlin, where he launched TIEFFREQUENT and the GOOEY Editz Series. Siggatunez also formed the experimental project SAVED MY LIFE in 2016 and developed a live set in 2022. In 2025, he joined SMALL GREAT THINGS as a resident DJ and artist.",img:"assets/images/djs/Siggatunez.jpg",sound:"https://soundcloud.com/siggatunez",insta:"https://www.instagram.com/siggatunez/?hl=en",expanded:false},

{name:"Skatman",info:"Born in Tunisia and based in Berlin, he has gained recognition for his distinctive style of electronic music which blends raw and unfiltered sounds with hypnotic and dreamy melodies. A sound that fuses the old-school with the contemporary. He has a substantial discography, featuring tracks on renowned labels such as Innervi-sions, Correspondent and TAU. He is also a resident DJ at the iconic Watergate club in Berlin, cementing his status as one of the most intriguing and captivating artists.",img:"assets/images/djs/Skatman.jpg",sound:"https://soundcloud.com/skatman-official",insta:"https://www.instagram.com/skatmanmusic/?hl=en",expanded:false},

{name:"Tomoki Tamura",info:"Tomoki Tamura, a DJ and producer from Osaka, rose through Japan’s club scene before moving to London in 2004, where he launched the Holic event series and Holic Trax label. Known for his deep house sound, he’s released over 50 records and collaborated with artists like Mr. G, Tuccillo, and Satoshi Tomiie. Now based in Berlin, he performs globally and explores ambient and jazz under his alias A Time Traveller. Offstage, he’s also an avid tennis player.",img:"assets/images/djs/Tomoki tamura.jpg",sound:"https://soundcloud.com/tomoki-tamura",insta:"https://www.instagram.com/tomoooooki__tamura/?hl=en",expanded:false},

{name:"TraumaMia",info:"TraumaMia is a Berlin-based DJ duo that mixes bouncy tech house with driving techno—groovy, energetic, and full of surprises. Their sets are packed with rolling beats, catchy melodies, and a dash of spicy vocals, topped off with playful samples and tight timing. As best friends both on and off stage, their chemistry is palpable and instantly connects with the crowd—whether on festival stages or in sweaty clubs. Deeply rooted in the FLINTA* scene, TraumaMia delivers not just sound, but also attitude: Dance, connect & shake up the patriarchy..",img:"assets/images/djs/Traumamia.jpg",sound:"https://soundcloud.com/trauma_mia",insta:"https://www.instagram.com/trauma_mia/?hl=en",expanded:false},
    
]
    